### ISSUE TITLE
Error with the version

### ISSUE THREAD

**Issue by Pythagoras19** [nel215/change_finder#2]
Hi, 

I used `pip install change_finder ` command for installation and I get the following error:

> Could not find a version that satisfies the requirement change_finder (from versions: )
> No matching distribution found for change_finder

I can not figure out the issue. I am using Ubuntu.

Thank you for your help.

**Comment by nel215** [comment]
It caused because I didn't build a wheel for python2.
I resolved the issue in #3 and uploaded a new version to pypi.
So, please retry to install the module.

**Comment by Pythagoras19** [comment]
Thanks, it works now.

**Comment by nel215** [comment]
It was good. Thank you for the your report.
