### ISSUE TITLE
Direction of the change

### ISSUE THREAD

**Issue by JPFrancoia** [nel215/change_finder#7]
Hi,

Your tool is really nice, it seems to work well.

Do you know if it's possible to tell the **direction** of the change, along with the likeliness of the change? By direction I mean "Increase" or "Decrease".

Thank you!

Also out of curiosity, are you one of the authors on the paper you refer to in the readme?

**Comment by nel215** [comment]
Hi

> Do you know if it's possible to tell the direction of the change, along with the likeliness of the change? By direction I mean "Increase" or "Decrease".

How about this?
```python
from change_finder import ChangeFinder
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
f, (ax1, ax2) = plt.subplots(2, 1)
f.subplots_adjust(hspace=0.4)
points = np.concatenate([
    np.random.normal(1, 0.1, 100),
    np.random.normal(-1, 0.1, 100),
    np.random.normal(1, 0.1, 100),
])
ax1.plot(points)
ax1.set_title("data point")

cf = ChangeFinder()
scores = np.array([cf.update(p) for p in points])
diff = points - np.roll(points, 1)
ax2.plot(scores * diff)
ax2.set_title("anomaly score")
plt.savefig('foo.png')
```
![foo](https://user-images.githubusercontent.com/1425061/48480832-f6c50400-e84e-11e8-90f7-3413d6b548f7.png)

> Also out of curiosity, are you one of the authors on the paper you refer to in the readme?

No.

**Comment by JPFrancoia** [comment]
Thanks!
